### ISSUE TITLE
drop can only be used in world_the_end(i don't know the name of it)

### ISSUE THREAD

**Issue by hseermc** [LOOHP/InteractionVisualizer#110]
item drop can only be used in world_the_end.(i don't know the name of it)
![image](https://github.com/LOOHP/InteractionVisualizer/assets/143265074/ebdc738a-bb86-4e01-8289-3d63117c0eed)
In world and world_nether, i drop an item but there is nothing on it.
![image](https://github.com/LOOHP/InteractionVisualizer/assets/143265074/73db7359-46b9-43fd-8335-ab1613726721)
Sometimes it can work well, sometimes it can't work.i don't know why.(sorry my poor English)

**Comment by hseermc** [comment]
sometimes i restart the server,the visual entities of drop item will disappear. there are many players in my server.can you add /iv reload to reload the visual entities? restart is inconvenience

**Comment by RobZenFL** [comment]
We also have the error, but in none of our worlds the display works. No error messages.

Server version:
Paper version git-Paper-424 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 37df121)

IV version:
1.18.8.0

**Comment by hseermc** [comment]
if i force shutdown my server then start it or delete the database and restart,it will work for a little time then have the same error
