### ISSUE TITLE
[Suggest]Let the books on Lectern display content

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#12]
Recently I saw a good mod content, it can make the content of the book displayed on Lectern, I do n’t know if this function can be achieved through the plugin
![2 3A$TPW{4RU G3 W1T_CHY](https://user-images.githubusercontent.com/41251296/79217569-aa398a00-7e81-11ea-92e4-fd07c8ff285a.jpg)

**Comment by LOOHP** [comment]
That's really cool, tho I can't really think of a way to implement this. Is it possible to have text this small in vanilla Minecraft?

**Comment by BackWheel** [comment]
In my opinion, the vanilla version does not seem to have such a small font, but I do n’t know much about plugin development, I do n’t know if the plugin can produce such content.If it does n’t work for the time being, you can consider keeping this suggestion, and add it to the plugin if you have a chance to realize it in the future.

**Comment by LOOHP** [comment]
Alright, but it doesn't look like it is possible for now, will keep an eye out.
