### ISSUE TITLE
Item despawn timer goes backwards (Paper 1.21.3)

### ISSUE THREAD

**Issue by dnchshrp** [LOOHP/InteractionVisualizer#126]
For some reason the item despawn timer goes in an opposide direction which makes it useless. I've first encountered on a private SMP but I could reproduce the bug on Paper with the default configs and without any other plugins.

Demonstration: https://github.com/user-attachments/assets/3098b270-6613-4908-b629-644aed29280f

**Comment by LOOHP** [comment]
Thank you for your report and clear demonstration!
