### ISSUE TITLE
Music disc names don't show correct

### ISSUE THREAD

**Issue by AsphaltExpert** [LOOHP/InteractionVisualizer#127]
So if I put a music disc in a jukebox it says "item.minecraft.music_disc_13.desc" in this case for disc 13.
This happens in any case for music discs on a Paper 1.21.3 Server.

![Screenshot 2024-11-27 004721](https://github.com/user-attachments/assets/18240332-8ebe-41b8-9ff5-ad2311588a7c)

I also tested this in 1.21.1 where it seems to work well.

**Comment by LOOHP** [comment]
Thank you for your report!
