### ISSUE TITLE
[BUG] Movement Buggy

### ISSUE THREAD

**Issue by AsphaltExpert** [LOOHP/InteractionVisualizer#128]
Hey there with another bug

So I'm experiencing a bug where movement is weird/slow.

https://github.com/user-attachments/assets/0e3d2453-c62e-4d47-976b-e879bd5cc9cb

For me, it is only when I play with a 1.21 Client on a 1.21.3 Server with ViaVersion, but I also read that someone has this in 1.21.3 on your Discord in the #interactionvisualizer channel.

**Comment by LOOHP** [comment]
Fixed by https://github.com/ViaVersion/ViaBackwards/issues/922
