### ISSUE TITLE
[Suggest]More realistic drops & Tool display rack

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#13]
I'm not sure if the actual purpose of this plugin is here, but I still want to make this suggestion. Recently, I saw a plug-in function, it should be realized through armor stand, it can make the items dropped more real, just like this picture, I wonder if you are considering adding such content?
![image](https://user-images.githubusercontent.com/41251296/79299369-70ff2980-7f16-11ea-8dd8-50ef68b4cfaa.png)

**Comment by BackWheel** [comment]
If you consider adding this content, I think the following functions can be added on this basis：
1.When the same drop appears in a place, it should be merged, and the name and number of items 
   are displayed through the hologram
2.More realistic drop method, for example, the sword can be inserted on the ground, etc.

**Comment by BackWheel** [comment]
New suggestion: I just saw a function on another server, it can use Tripwire Hook as a shelf to hang some tools, maybe consider adding this function?
![image](https://user-images.githubusercontent.com/41251296/79299895-c4be4280-7f17-11ea-918a-17638a447e4c.png)

**Comment by LOOHP** [comment]
These features seemed to be outside of the aim off the plugin of just visualizing existing features. The are quite cool tho of course. I'll be closing this for now.
