### ISSUE TITLE
Server lags because of wrong usage of BlockingQueue

### ISSUE THREAD

**Issue by nicuch** [LOOHP/InteractionVisualizer#14]
https://github.com/LOOHP/InteractionVisualizer/blob/42017f2d1513f5051713b0ded9cd1356b147c059/src/com/loohp/interactionvisualizer/InteractionVisualizer.java#L63

Please consider using [ConcurrentLinkedQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html) that doesn't block the main thread [for 2 ms for every poll](https://github.com/LOOHP/InteractionVisualizer/blob/42017f2d1513f5051713b0ded9cd1356b147c059/src/com/loohp/interactionvisualizer/InteractionVisualizer.java#L193) if the server already lags.

**Comment by LOOHP** [comment]
Thanks for pointing that out, will be using that in 1.8.5!

**Comment by LOOHP** [comment]
In fact, I found a better way to do things without going over chunks. Thanks for telling me that still.

**Comment by nicuch** [comment]
Neat! Can't wait to test the performance :D
