### ISSUE TITLE
[Suggestion] LightAPI

### ISSUE THREAD

**Issue by nicuch** [LOOHP/InteractionVisualizer#17]
Please make light api optional, not required, thank you!

**Comment by LOOHP** [comment]
The problem with that is if you don't modify the block light level, the armor stands gets dark for some case which looks awful. And modifying the world light level (either for real or through packets) all seemed horrible difficult.

**Comment by nicuch** [comment]
Ah, I see.

**Comment by LOOHP** [comment]
If I can somehow understand how chunk light update packets work, I'll be happy to drop LightAPI.

**Comment by BackWheel** [comment]
If this is the best way, maybe you can refer to this plugin?https://www.spigotmc.org/resources/public-crafting-tables.50686/ @LOOHP

**Comment by LOOHP** [comment]
I would love to give the plugin a try but it's a paid plugin..

**Comment by BackWheel** [comment]
https://www.spigotmc.org/resources/craftdisplay.46811/

You can consider reopening this question, I also found a free plugin with similar functions, this plugin does not make use of LightAPI.

**Comment by nicuch** [comment]
That plugin is creating armorstands that are not actually on the server, probably that's why.

**Comment by LOOHP** [comment]
![2020-04-18_18 01 46](https://user-images.githubusercontent.com/22975196/79634690-bafa4080-819e-11ea-8927-592c457b483f.png)
That's why the plugin actually has the problem as well. (running 5.2,0 on 1.12.2)

**Comment by BackWheel** [comment]
Okay, but I think LightAPI can also be made optional, but it ’s just a reminder that users have the opportunity to darken some of the displayed items.

**Comment by LOOHP** [comment]
I could assure you that there will be people who don't read and leave 1-star reviews pointing this out. Also, why would anyone want to use a crafting table that darkens like this.

**Comment by BackWheel** [comment]
I understand, then I hope to deal with this problem in the future XD

**Comment by LOOHP** [comment]
I've looked into the light update packet and it seemed not very practical to send. Writing the code in NMS ourselves could be done but it would probably be not as efficient as the API as it has been developed for much longer. Closing this for now.
