### ISSUE TITLE
[High Usage] Please take a look at this timings

### ISSUE THREAD

**Issue by nicuch** [LOOHP/InteractionVisualizer#18]
https://timings.aikar.co/?id=ae0f8dfaf674440199a44bdb92417dfb#plugins

What you'll see, is your plugin. You might be asking, why your plugin has so much high usage?
Because you're calling `world.getBlockAt(position)` for every block (furnaces, looms, etc) that are in unloaded chunks and that causes the chunk to load again. Also, storing the Block object in a hashmap, its also a bad idea sometimes, and can prevent chunks from unloading. My server has over 100 plugins, and some plugins relies on chunk loading, but that are plugins that I can't do anything about them, nor their plugin authors (Citizens, MythicMobs, etc).
What am I trying to say is that, everytime your plugin runs the gc() methods, the chunks are loaded again, the other plugins catches the chunks loading, and that causes masive lag, just because your are trying to clean the memory (and that's fine).
What can YOU do, to prevent chunks from loading again when not necessary?
Do not use the Block object, nor the Entity object, nor ANY Location object. Never to store them in hashmaps, never to call them when trying to clean (when not necessary). Instead, convert them to objects that are not related to BukkitAPI.

**Comment by LOOHP** [comment]
The gc should remove all reference of furnaces etc in unloaded chunks once it happens, so that shouldn't be causing chunks to load. What is causing the chunks to load is the time between the player unloads the chunks and the gc happens, in this small period of time the chunks keep getting loaded. I guess I can either force a gc everytime a chunk unloads or speed up the gc.

**Comment by LOOHP** [comment]
It looks as if I have patched all of the places that could lead to chunk loading, at least all that I can find, give it a try and see if it is any better :)

**Comment by nicuch** [comment]
I see that you don't pretty understand hashing in java, and that's a bad thing. Any hash you store (the object array), need to have equals() and hashCode() implemented. I'm still gonna test it, however, honestly I'm still not pretty sure about your code.

**Comment by LOOHP** [comment]
Apologise, if I do not fully understand how everything works, from what I know is that, if I need to override default equals, then I have to override hashCode. But must I override equals? Can't I just use the default equals and not having to override hashCode as well?

**Comment by nicuch** [comment]
Firsty, let's create a new object for you, don't use the java Object directly, never do that, because of performance issues. The object you'll create as a key for hashing, needs to have equals and hashcode override, if you're using java's generated equals, then java will only check the memory location where the object is stored, and not the actual values stored in the object (Object.equals(object) is the same as saying Object == object), and that causes duplications.

**Comment by nicuch** [comment]
I would pretty love to help you code this, but aparently IntelliJ have some problems, and I forgot how to use Eclipse (I didn't use it for 3 years now).

**Comment by LOOHP** [comment]
Yea, that's why I am not using the world object directly in the PlayerRangeManager. I put the `{worlduuid, intchunkx, intchunkz}` array into a hashset and later check if the array exists in the set with `Arrays.equals(a, b)` as it is a shallowequals.
