### ISSUE TITLE
Suggestions for plugins

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#2]
Hope to add the following functions to the plugin:
1.Can store the item data of Crafting Table, so that players can still put the items on the Crafting Table 
   after closing the GUI.
2.Support the push of the piston.
3.Provide a hologram to show the growth rate of crops.
4.Displays the name of the final synthesized item of Crafting Table.(Maybe furnaces and anvils can also 
   add this?)

**Comment by LOOHP** [comment]
Feature 2 added in 1.1.0
Feature 4 being added.
Thanks for the suggestions!
Although one thing, wouldn't a hologram for each crop block be extremely annoying?

**Comment by BackWheel** [comment]
If the player is only allowed to aim the sight at the crops, the hologram will be displayed, so there may be no such problem.

**Comment by LOOHP** [comment]
Alright, I think about that.

**Comment by BackWheel** [comment]
The first and fourth suggestions are actually from a paid plugin I bought before: https://www.spigotmc.org/resources/public-crafting-tables.50686/

**Comment by LOOHP** [comment]
About the first one, I'm not so sure if it fits what my plugin is trying to achieve, as for the fourth one, isn't it already in the plugin rn?

**Comment by LOOHP** [comment]
I'll keep the ideas in mind and add them if I see fit, closing this for now.
