### ISSUE TITLE
BeaconPlus2 Support

### ISSUE THREAD

**Issue by Nachtalb** [LOOHP/InteractionVisualizer#21]
Would it be possible to add https://www.spigotmc.org/resources/beaconplus-2-upgradable-beacons-for-your-server-15-off.67056/ support to get the range right and the power level instead of the tier?

Range
---
![Inked2020-04-23_12 12 17_LI](https://user-images.githubusercontent.com/9467802/80088106-59e6ba00-855c-11ea-8e4f-c028393539c7.jpg)

Power Level
---
![Inked2020-04-23_12 15 26_LI](https://user-images.githubusercontent.com/9467802/80088123-5d7a4100-855c-11ea-8210-812236d01d41.jpg)

Current Visualizer
---
![Inked2020-04-23_12 12 14_LI](https://user-images.githubusercontent.com/9467802/80088115-5bb07d80-855c-11ea-9f3f-7480700faeb3.jpg)

**Comment by LOOHP** [comment]
That's a cool plugin. Tho, unfortunately, it seemed impossible as
1. on the resource page, it looks as if only v1 as an API
2. it is a paid resource and I do not own it, and the author didn't release a public API

Also, I seemed to have some problem loading your images.

**Comment by Nachtalb** [comment]
Sooooo...

I have made a branch with the said integration. Though I haven't done anything with Java in years so it might not be that good. 

In addition, I have extended the README a bit and put in a notice about the BP2 integration.

If you want I can make a PR, though as you said and as stated in the README it can break with any new BP2 version because there is no official API.

Here a pic of the integration: 
![image](https://user-images.githubusercontent.com/9467802/80149251-a232c600-85b6-11ea-8fb1-c6a49655be94.png)


Readme etc.: https://github.com/LOOHP/InteractionVisualizer/compare/master...Nachtalb:na/update-info
BP2: https://github.com/Nachtalb/InteractionVisualizer/compare/na/update-info...Nachtalb:na/beaconplus2-support

**Comment by LOOHP** [comment]
I'm not sure if merging the beacon thing is the best action as you stated.
You can always fork that portion of the code, and I don't plan on changing beacons to much anyway.
BTW you can called the `RomanNumberUtils.toRoman(int number)` if you want the traditional Minecraft way of displaying numbers.

**Comment by Nachtalb** [comment]
I'll use it for now on my own server. Thanks for the hint with the roman numerals!

I'll close this for now. Maybe they will add an official API at some point in the future.
