### ISSUE TITLE
`/plugman reload` support

### ISSUE THREAD

**Issue by Nachtalb** [LOOHP/InteractionVisualizer#22]
`/plugman reload` reloads the whole plugin - not just disabling and enabling it (like `/plugman restart`, it reloads the whole `jar` file. That means that you can update plugins without restarting the whole server, which is quite nice!. Though the problem atm is that for some reason InteractionVisualizer does not seem to restart the scheduler that updates the visualizations (like the beacon info). I haven't looked into it at all tbh but I guess the plugin only starts the schedule on player login(?). Anyways it would be nice if that worked. 

I saw somewhere (spigot review or so) that you consider building an auto-updater into the plugin. When you do that you would probably run into the same problem...

If you want I can take a look at it.

Plugman https://dev.bukkit.org/projects/plugman

**Comment by LOOHP** [comment]
I guess the only thing that doesn't refresh is the loadplayer code in PlayerJoinEvent, so the easiest way to get around this would be to go over all online players when the plugin reloads.

**Comment by LOOHP** [comment]
Plugman reload should work on the latest versions :)
