### ISSUE TITLE
[suggest]More complete enchantment information display

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#25]
After I try to enchant my equipment with an enchanting table, when I enchant more than one enchantment, the hologram of the plug-in seems to show only one of them? Maybe there is a way to show them all?

**Comment by LOOHP** [comment]
That is possible, although I will need to make use of armorstands instead of just naming the item. I'll consider adding that in the future. Right now, the plugin chooses the highest level enchantment to display.

**Comment by BackWheel** [comment]
Ok,thanks

**Comment by LOOHP** [comment]
Added in 1.10.13.
