### ISSUE TITLE
[Suggestion] Paper Async Chunks

### ISSUE THREAD

**Issue by ishland** [LOOHP/InteractionVisualizer#26]
Using Paper Async Chunks to improve performance.

**Comment by LOOHP** [comment]
The plugin shouldn't be loading any chunks at the moment. Measures are in place to make the plugin only work with already loaded chunks. Can you elaborate a bit more?

**Comment by ishland** [comment]
The plugin sometimes do sync loads.

**Comment by LOOHP** [comment]
Do you have anything I can look into? For example timings?

**Comment by ishland** [comment]
It can only happen at a very extreme settings and rarely happen so I am closing it.
