### ISSUE TITLE
Name tags

### ISSUE THREAD

**Issue by Alekhedjran** [LOOHP/InteractionVisualizer#27]
Hello i run a faction server and i love this plugin but i cant seem to get rid of name tags on blocks. It gives up certain postions inside peoples bases! is their an option im not seeing to disable this? if not can you make an option to disable nametags?

**Comment by LOOHP** [comment]
That's a good point, I have an idea in mind, I'll get back to you after I see if my idea actually works.

**Comment by LOOHP** [comment]
Hmm my idea doesn't quite work. Oh well!

Actually, you can just turn off holograms in the module section in the config I believe.
