### ISSUE TITLE
Better perfomance?

### ISSUE THREAD

**Issue by Volgeop** [LOOHP/InteractionVisualizer#31]
Hi, I looked into my timings and it seems that interactionvisualisier is the most heavy plugin that I have by timings. https://timings.aikar.co/?id=3c4e4e51db7245a4b19f2a8a75d155af#timings
count(226375)  total(2.50% 19.705s, 3.03% of tick)avg(0.09ms per - 1.52ms/17.42 per tick

When you sort it by timings. Sometimes there are also peeks. Do you think that you can try improve it somehow?

**Comment by LOOHP** [comment]
Doesn't look terribly heavy considering the constant use of such blocks. That said tho, I've actively improved performance over the different versions and will continue to do so. That means performance should get better version by version.

In the meantime, you can play around with the settings in the config regarding the update periods of different modules to suit the needs of your server. :)

**Comment by Volgeop** [comment]
And do you suggest me changing any config options or it's necessary?

**Comment by Volgeop** [comment]
InteractionVisualizer::Task: com.loohp.interactionvisualizer.Managers.LightManager$$Lambda$6208 (interval:10)count(35)  total(5.30% 0.27s, 8.72% of tick)avg(7.73ms per - 4.36ms/0.56 per tick
https://timings.aikar.co/?id=ffebd2746c4f4f0e8e5649c286777f1e

Still ok? IK that these are short timings, but I have big tps peeks when server starts

**Comment by LOOHP** [comment]
You are not required to change the update periods in the config. But since every server is different, the options are there for you to customize.

I suggest turning down the Light Update Period by the looks of your timings report.

**Comment by Volgeop** [comment]
How can I turn it down? There's just:
LightUpdate:
  Period: 10

What do you suggest there?

**Comment by LOOHP** [comment]
That said tho I am aware that Light Update uses quite a bit of performance as it is required to be update in sync. I'll see if I can improve it in the future.

**Comment by Volgeop** [comment]
And should I change period to another number? If yes, which one?

**Comment by LOOHP** [comment]
Just increase the number until you are comfortable.
The good news is tho, according to the new 1.16.2 pre-release, light updates might not be needed anymore as marker armorstands no longer darkens

**Comment by Volgeop** [comment]
@LOOHP having this https://imgur.com/gufxMeW https://timings.aikar.co/?id=fc31cc2ca62948b5bc32ad4a076f2405

We will see if the new version will helps, should be released today? Is it still due to armor stands?

**Comment by LOOHP** [comment]
Actually, can you show me your config for a quick look?

**Comment by Volgeop** [comment]
https://pastebin.com/fnJ0kMy8

**Comment by LOOHP** [comment]
Try setting to this
```
TileEntityUpdate:
  LoadTileEntitiesAsync: true
  ChunksPerTick: 1
```
See if it is any better.

**Comment by bobhenl** [comment]
https://timings.aikar.co/?id=ab05327864a54db286815a8732a2044b
![image](https://user-images.githubusercontent.com/18662086/99922951-771e7980-2d33-11eb-8559-115ae17578d6.png)


@LOOHP ?
