### ISSUE TITLE
Items not disappearing

### ISSUE THREAD

**Issue by Gracv** [LOOHP/InteractionVisualizer#32]
After using enchant tables, sometimes items will not disappear
Server version: 1.16.1
Plugin version: 1.13.6

![image](https://user-images.githubusercontent.com/37741582/90676519-6d7d0580-e25c-11ea-8428-4a865eb6c219.png)
![image](https://user-images.githubusercontent.com/37741582/90676546-7968c780-e25c-11ea-9c1d-c66b8cf699eb.png)

**Comment by Gracv** [comment]
How can I kill this existing items? /minecraft:kill @e[type=minecraft:item] doesn't work on them

**Comment by LOOHP** [comment]
They don't exist on the server, therefore it cannot be killed.

Can you give this dev build a try and see if it fixes the issue?
[InteractionVisualizer-1.13.6.zip](https://github.com/LOOHP/InteractionVisualizer/files/5100581/InteractionVisualizer-1.13.6.zip)

**Comment by LOOHP** [comment]
Did it work?

**Comment by LOOHP** [comment]
Did the issue got fixed?

**Comment by LOOHP** [comment]
Closing this for now
