### ISSUE TITLE
Error spam 

### ISSUE THREAD

**Issue by LoneDev6** [LOOHP/InteractionVisualizer#34]
- Spigot 1.16.2 - This server is running CraftBukkit version git-Spigot-b5a13e6-0491200 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
- latest Protocollib build
- error spam: https://pastebin.com/7PdmKLpJ

**Comment by LOOHP** [comment]
This seems to be a bug on protocollib. I've tested and it seemed like the error only shows up when the plugin is first started and it doesn't affect the functionality of the plugin. For now, you can safely ignore it.

**Comment by LoneDev6** [comment]
Thanks a lot, I will ignore it

**Comment by LOOHP** [comment]
You are using the latest protocollib build #478 right?

**Comment by LoneDev6** [comment]
ProtocolLib version 4.6.0-SNAPSHOT-b478

**Comment by LOOHP** [comment]
Fixed in 1.13.7
