### ISSUE TITLE
Small optimization needed

### ISSUE THREAD

**Issue by MastoryMd5** [LOOHP/InteractionVisualizer#35]
Amazing plugin but it should be optimized a little bit.
https://timings.aikar.co/?id=9e8bd4575a0840e2ab62ad084b5c2242#plugins
As you can see from the timings the plugin takes an average if 170ms, it's not something too extreme but if it can be optimized it would be an amazing thing!

#edit 18/10/2020
https://timings.aikar.co/?id=b6da17a137f34601a8d7de6d30668a88
https://spark.lucko.me/#5GmvADiTrf
Had a tps drop due to interactor visualizer

**Comment by LOOHP** [comment]
The LightManager is a difficult thing to optimize, I'll slowly try to optimize it over time.
In the meantime, you can try lowering the light update rate in the config to see if that helps!

**Comment by LOOHP** [comment]
Closed due to inactivity.
