### ISSUE TITLE
[BUG]Method for maliciously manufacturing invisible armor stand

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#4]
I found that I can use a redstone machine to leave the display items on the Crafting Table in the form of armor racks. Please check this video for details:https://youtu.be/OldO8CloSa4

**Comment by LOOHP** [comment]
I see.. Does the armorstands persist after the player relog? Does the armorstands persist after server restart?

**Comment by LOOHP** [comment]
Confirmed

**Comment by BackWheel** [comment]
Hope to add a command to the plugin after this bug is fixed, so that we can delete the invisible armor stand generated by the plugin through the command

**Comment by LOOHP** [comment]
The bug has been fixed in 1.4.0 (https://github.com/LOOHP/InteractionVisualizer/releases/tag/v1.4.0)
For now, if you want to reset armorstands, you can use /iv toggle twice or rejoin.
