### ISSUE TITLE
ArmorStand Items and Holograms not showing 

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/InteractionVisualizer#44]
It seems like the effects for example showing how an item is crafted in a crafting table doesnt get shown. it shows the final product once you have a recipe in, but doesnt show the resources on the table 

progress bars also do not show, for example on beehives, furnaces, brewing stands

**Comment by LOOHP** [comment]
Did you disable the itemstand or hologram module in the config or through /iv toggle?

**Comment by JustJP2K** [comment]
i did not

**Comment by LOOHP** [comment]
Which server software and minecraft version are you using?

**Comment by JustJP2K** [comment]
paper 1.16.5 and on a linux server

**Comment by LOOHP** [comment]
I mean server software like Spigot or Paper etc.

**Comment by JustJP2K** [comment]
18.01 12:35:06 [Server] WARN Plugin InteractionVisualizer v1.14.2.1 generated an exception while executing task 1152250
18.01 12:35:06 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
18.01 12:35:06 [Server] INFO at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:77) ~[?:?]
18.01 12:35:06 [Server] INFO at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$11(PacketManager.java:279) ~[?:?]
18.01 12:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
18.01 12:35:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
18.01 12:35:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
18.01 12:35:06 [Server] WARN Plugin InteractionVisualizer v1.14.2.1 generated an exception while executing task 1152243
18.01 12:35:06 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
18.01 12:35:06 [Server] INFO at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:77) ~[?:?]
18.01 12:35:06 [Server] INFO at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$11(PacketManager.java:279) ~[?:?]
18.01 12:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-418]
18.01 12:35:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
18.01 12:35:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
18.01 12:35:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

this may help

**Comment by LOOHP** [comment]
You need to update protocollib to the latest dev build

**Comment by JustJP2K** [comment]
ah ok, thanks for your help! let me try that

**Comment by JustJP2K** [comment]
works! thank you a lot! :)
