### ISSUE TITLE
Getting this filling up console

### ISSUE THREAD

**Issue by Fantom250YT** [LOOHP/InteractionVisualizer#48]
Pastebin
https://pastebin.com/5EtYRQYG

**Comment by LOOHP** [comment]
You need to use the latest dev build of protocollib

**Comment by Fantom250YT** [comment]
okay

**Comment by Fantom250YT** [comment]
Still getting it filling up console?

**Comment by LOOHP** [comment]
what version of protocollib are you using?

**Comment by Fantom250YT** [comment]
4.5.1

**Comment by LOOHP** [comment]
The latest dev build is 4.6.0-SNAPSHOT

**Comment by Fantom250YT** [comment]
Thanks :)

**Comment by LOOHP** [comment]
Working?

**Comment by Fantom250YT** [comment]
yep, so far anyway

**Comment by LOOHP** [comment]
Alright, closing this for now.
