### ISSUE TITLE
A small question about water flow

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#5]
I found that I was able to let the suspended matter in the furnace be pushed by the water flow. Although he will automatically return to his original position after a period of time, I am not sure whether this problem can cause more bugs. Therefore, maybe we should prohibit these suspended solids from being driven by water flow? In addition, the piston can push the suspended solids.
https://youtu.be/5GzS3QnllY4

**Comment by LOOHP** [comment]
Unfortunately, it is the Minecraft client that believed the item had moved. In reality, the item isn't moved at all. So the movement is only visual. A simple relog or /iv toggle would bring the item back to where it is. It shouldn't cause any issue, at least it shouldn't in theory.

**Comment by LOOHP** [comment]
Alright I've added /iv refresh in 1.4.3 just in case
