### ISSUE TITLE
paper compatibility?

### ISSUE THREAD

**Issue by Drakemlumme** [LOOHP/InteractionVisualizer#50]
Your plugin is amazing, it fascinates me, I love it xD
but i think it is not compatible with paper.
The truth is that it works relatively well, the items appear floating properly, the villagers throw the items away, everything works fine except ... the textual part does not work, the furnances do not show the text, neither the note blocks, nor the beacons.
And in the console spam this without for:
https://pastebin.com/raw/TarzaApg
I will try to fix the console spam with some plugin, because I am not going to stop using your plugin because it is just great.
But it would be nice if there was compatibility with paper (if that is the problem) 
ty ♥

**Comment by LOOHP** [comment]
The plugin is 100% compatible with paper. The problem is that you are not using the latest dev build of protocollib, try updating it.

**Comment by Drakemlumme** [comment]
in fact you're right, it worked! I love you xD
