### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Dreeam-qwq** [LOOHP/InteractionVisualizer#51]
server version paper 1.16.4

when player uses the workbench or furnace, their coord will be leaked.

---
1. use Wurst Client to enter the server
2. open the "player finder"
3. waiting a player uses the workbench, then you can get his XYZ coord.

**Comment by LOOHP** [comment]
Is the range unlimited or just a set amount of blocks?

**Comment by Dreeam-qwq** [comment]
> 
> 
> Is the range unlimited or just a set amount of blocks?

unlimited.

**Comment by LOOHP** [comment]
Which version of the plugin are you using?
Can you show me your InteractionVisualizer config and your spigot.yml ?

**Comment by Dreeam-qwq** [comment]
> 
> 
> Which version of the plugin are you using?
> Can you show me your InteractionVisualizer config and your spigot.yml ?

the plugin version is 1.14.4.1

spigot.yml
https://pastebin.com/LHavCe3e

config
https://pastebin.com/nSS8yUnG

**Comment by LOOHP** [comment]
Emm.. according to your config, only players within 48 blocks would be notified.

**Comment by Dreeam-qwq** [comment]
> 
> 
> Emm.. according to your config, only players within 48 blocks would be notified.

I tested it ，I tp to the 9999, 100, 9999, but I can use this Hack Client to detect the player's coord(around the spawn) when they used the workbench or something．　maybe I get something wrong for my config?

**Comment by LOOHP** [comment]
Do you get the player's coords when they open the table? Or when they click on the table? Or when they craft? Which stage is the coords leaked?

**Comment by Dreeam-qwq** [comment]
> 
> 
> Do you get the player's coords when they open the table? Or when they click on the table? Or when they craft? Which stage is the coords leaked?

When they get the items after crafting.

**Comment by LOOHP** [comment]
Alright, I've made a few changes to the code, can you give version 1.14.4.2 a try and see if it works?
