### ISSUE TITLE
[1.14.5.1] multiple exceptions while executing task 

### ISSUE THREAD

**Issue by Ryoyo2** [LOOHP/InteractionVisualizer#54]
The plugin keeps throwing errors from different tasks at me multiple times a minute:
https://pastebin.com/373SqAew

I don't know what to make of it but hopefully you can?

Thanks in advance,
Ryoyo

**Comment by LOOHP** [comment]
Hello! Can you give this build a try?

https://drive.google.com/file/d/1PVRjCMza_839nQfM3roKDP1336Eh_iIA/view?usp=sharing

**Comment by Ryoyo2** [comment]
Hey. I believe that has fixed the issue. Thanks!

**Comment by LOOHP** [comment]
Great!
