### ISSUE TITLE
1.17 support issue

### ISSUE THREAD

**Issue by EuanM199** [LOOHP/InteractionVisualizer#58]
hey, First of all gotta say i love the plugin, both me and my players love it, having this issue on 1.17 with latest proticol lib
see error here ([https://bin.bloom.host/cicameyahu.md](https://bin.bloom.host/cicameyahu.md)) 

thanks!

**Comment by EuanM199** [comment]
oh and this error too [https://bin.bloom.host/ukuzovadof.properties](https://bin.bloom.host/ukuzovadof.properties)

**Comment by LOOHP** [comment]
You can view progress of 1.17 updates on my discord
http://dev.discord.loohpjames.com
