### ISSUE TITLE
Future request - Toggle commands for all funktions

### ISSUE THREAD

**Issue by ErythroCraft** [LOOHP/InteractionVisualizer#59]
Hi.

Maybe you can create an update for [ interactionvisualizer toggle itemstand { block } ]
So, the idea is simple, but not simple for me to realize.

I would like to add another GUI to my player GUI [player setting] where players can use all toggle commands of allowed plugins. In addition, it should be possible to allow toggle {block}. In addition, toggle {blocks} should be able to be switched on or off in the config.

To do this, the command and the command would first have to be changed from
[/ interactionvisualizer] to [/ iv]
and
[interactionvisualizer.toggle] to
[interactionvisualizer.toggle. {itemstand / itemdrop / hologram / all}. {block}]

It could look like this:

example config
  Blocks:
    Anvil:
      Enabled: true/false
      Toggle: true/false

interactionvisualizer.toggle.all
  - /iv toggle all

interactionvisualizer.toggle.itemstand.all
  - /iv toggle itemstand all
interactionvisualizer.toggle.itemstand.block
  - interactionvisualizer.toggle.itemstand.anvil
  - /iv toggle itemstand anvil
  - interactionvisualizer.toggle.itemstand.banner
  - /iv toggle itemstand banner
  - interactionvisualizer.toggle.itemstand.beacon
  - /iv toggle itemstand beacon
  - interactionvisualizer.toggle.itemstand.bee_hive
  - /iv toggle itemstand bee_hive
  - interactionvisualizer.toggle.itemstand.bee_nest
  - /iv toggle itemstand bee_nest
  - interactionvisualizer.toggle.itemstand.blast_furnace
  - /iv toggle itemstand blast_furnace
  - interactionvisualizer.toggle.itemstand.brewing_stand
  - /iv toggle itemstand brewing_stand
  - interactionvisualizer.toggle.itemstand.campfire
  - /iv toggle itemstand campfire
  - interactionvisualizer.toggle.itemstand.cartography_table
  - /iv toggle itemstand cartography_table
  - interactionvisualizer.toggle.itemstand.chest
  - /iv toggle itemstand chest
  - interactionvisualizer.toggle.itemstand.conduit
  - /iv toggle itemstand conduit
  - interactionvisualizer.toggle.itemstand.craftingTable
  - /iv toggle itemstand table
  - interactionvisualizer.toggle.itemstand.dispenser
  - /iv toggle itemstand dispenser
  - interactionvisualizer.toggle.itemstand.double_chest
  - /iv toggle itemstand double_chest
  - interactionvisualizer.toggle.itemstand.dropper
  - /iv toggle itemstand dropper
  - interactionvisualizer.toggle.itemstand.enchantment_table
  - /iv toggle itemstand enchantment_table
interactionvisualizer.toggle.itemstand.entity
  - interactionvisualizer.toggle.itemstand.entity.item
  - /iv toggle itemstand entity item 
  - interactionvisualizer.toggle.itemstand.entity.villager
  - /iv toggle itemstand entity villager

interactionvisualizer.toggle.itemdrop.all
interactionvisualizer.toggle.itemdrop.block
  - interactionvisualizer.toggle.itemdrop.anvil
  - /iv toggle itemdrop anvil
  - interactionvisualizer.toggle.itemdrop.banner
  - /iv toggle itemdrop banner
  - interactionvisualizer.toggle.itemdrop.beacon
  - /iv toggle itemdrop beacon
  - interactionvisualizer.toggle.itemdrop.bee_hive
  - /iv toggle itemdrop bee_hive
  - interactionvisualizer.toggle.itemdrop.bee_nest
  - /iv toggle itemdrop bee_nest
  - interactionvisualizer.toggle.itemdrop.blast_furnace
  - /iv toggle itemdrop blast_furnace
  - interactionvisualizer.toggle.itemdrop.brewing_stand
  - /iv toggle itemdrop brewing_stand
  - interactionvisualizer.toggle.itemdrop.campfire
  - /iv toggle itemdrop campfire
  - interactionvisualizer.toggle.itemdrop.cartography_table
  - /iv toggle itemdrop cartography_table
  - interactionvisualizer.toggle.itemdrop.chest
  - /iv toggle itemdrop chest
  - interactionvisualizer.toggle.itemdrop.conduit
  - /iv toggle itemdrop conduit
  - interactionvisualizer.toggle.itemdrop.crafting_able
  - /iv toggle itemdrop table
  - interactionvisualizer.toggle.itemdrop.dispenser
  - /iv toggle itemdrop dispenser
  - interactionvisualizer.toggle.itemdrop.double_chest
  - /iv toggle itemdrop double_chest
  - interactionvisualizer.toggle.itemdrop.dropper
  - /iv toggle itemdrop dropper
  - interactionvisualizer.toggle.itemdrop.enchantment_table
  - /iv toggle itemdrop enchantment_table
interactionvisualizer.toggle.itemdrop.entity
  - interactionvisualizer.toggle.itemdrop.entity.item
  - /iv toggle itemdrop entity item 
  - interactionvisualizer.toggle.itemdrop.entity.villager
  - /iv toggle itemdrop entity villager

interactionvisualizer.toggle.hologram.all
interactionvisualizer.toggle.hologram.block
  - interactionvisualizer.toggle.hologram.anvil
  - /iv toggle hologram anvil
  - interactionvisualizer.toggle.hologram.banner
  - /iv toggle hologram banner
  - interactionvisualizer.toggle.hologram.beacon
  - /iv toggle hologram beacon
  - interactionvisualizer.toggle.hologram.bee_hive
  - /iv toggle hologram bee_hive
  - interactionvisualizer.toggle.hologram.bee_nest
  - /iv toggle hologram bee_nest
  - interactionvisualizer.toggle.hologram.blast_furnace
  - /iv toggle hologram blast_furnace
  - interactionvisualizer.toggle.hologram.brewing_stand
  - /iv toggle hologram brewing_stand
  - interactionvisualizer.toggle.hologram.campfire
  - /iv toggle hologram campfire
  - interactionvisualizer.toggle.hologram.cartography_table
  - /iv toggle hologram cartography_table
  - interactionvisualizer.toggle.hologram.chest
  - /iv toggle hologram chest
  - interactionvisualizer.toggle.hologram.conduit
  - /iv toggle hologram conduit
  - interactionvisualizer.toggle.hologram.crafting_able
  - /iv toggle hologram table
  - interactionvisualizer.toggle.hologram.dispenser
  - /iv toggle hologram dispenser
  - interactionvisualizer.toggle.hologram.double_chest
  - /iv toggle hologram double_chest
  - interactionvisualizer.toggle.hologram.dropper
  - /iv toggle hologram dropper
  - interactionvisualizer.toggle.hologram.enchantment_table
  - /iv toggle hologram enchantment_table
interactionvisualizer.toggle.hologram.entity
  - interactionvisualizer.toggle.hologram.entity.item
  - /iv toggle hologram entity item 
  - interactionvisualizer.toggle.hologram.entity.villager
  - /iv toggle hologram entity item 

**After this you can give more and more customizables**

for example:
  - interactionvisualizer.toggle.hologram.entity.item.{item_name}
  - interactionvisualizer.toggle.hologram.entity.entity_name

**Comment by LOOHP** [comment]
Per entry toggle is added 1.16.0, tho not the permissions.

**Comment by ErythroCraft** [comment]
ok
