### ISSUE TITLE
Feature Request: Additional Enchantment Table options

### ISSUE THREAD

**Issue by Brickwrath** [LOOHP/InteractionVisualizer#60]
From what I have tested, the Enchantment Table features are simply on and off.
I am hoping to be able to have items visibly interact with the table (as on by default) and get the really nice enchantment animation, but *not* have the floating holograms with the enchant stats.
Even with `Modules: Hologram: Enabled: false`, as long as `Enchantment Table: Enabled:` is `true`, this appears.
Hoping for an `Option:` for something like `EnchantmentTableText:` so only that feature could be disabled?

Thank you for your time and consideration; really legendary plugin here!

**Comment by LOOHP** [comment]
EnchantmentTable enchantments display should now part of the Hologram module since 1.16.0.4

**Comment by Brickwrath** [comment]
Could you share what config options you are expecting used to accomplish this?
I have updated to latest server, downloaded latest LightAPI and Hologram (confirmed v. 1.16.0.4) and generated a new config.
With `Modules: Hologram: Enabled: false`, the Enchantment Table still shows its holograms `X Enchantment Levels` `Enchantment I` `Enchantment II` if `EnchantmentTable: Enabled: true`

I am assuming that several other blocks, like the lectern and beehives (which is enabled and showing Holograms despite the above Holograms being Disabled) are _not_ expected to disable their Holograms since that's their only function?

**Comment by LOOHP** [comment]
There seems to be a bug. Try having `Modules.Hologram.Enabled: false` with `Blocks.EnchantmentTable.Enabled: true` again with version 1.16.0.5

**Comment by Brickwrath** [comment]
Success!  Looks like everything's operating as expected.

Thanks so much for the timely support, it really means a lot!

**Comment by LOOHP** [comment]
No problem :)
