### ISSUE TITLE
MySQL Console Error `Table 'minecraft.STATUS_LOCK' doesn't exist`

### ISSUE THREAD

**Issue by Zoro-6191** [LOOHP/InteractionVisualizer#61]
Hi, looks like there's a bit of an issue with creating the table
I just entered the correct mysql database details in the config

At the time of launch:
![image](https://user-images.githubusercontent.com/52291201/124030892-45316c00-da14-11eb-82a1-456b4bcf5a45.png)

and on exit:
![image](https://user-images.githubusercontent.com/52291201/124030969-5da18680-da14-11eb-9395-cb5b20c6dfd8.png)

these got printed atleast 50 more times in the console

Paper 1.17#63

**Comment by LOOHP** [comment]
Are you using InteractionVisualizer 1.16.0.0? Later dev builds after 1.16.0.1 should have already fixed that.

**Comment by Zoro-6191** [comment]
yeah was running 1.16.0.0
updated to 1.16.0.5 and it doesn't give errors anymore
thanks 👍🏻
