### ISSUE TITLE
Small issue with `/iv toggle`

### ISSUE THREAD

**Issue by Zoro-6191** [LOOHP/InteractionVisualizer#62]
Hi, I just typed `/iv toggle hologram bee_hive false`
The command worked fine, but the message in chat was `Toggled %s off`

I'm guessing that `%s` was supposed to be replaced by some text, which doesnt seem to happen

I replaced `%s` with `%s%` in the config, didn't help

![image](https://user-images.githubusercontent.com/52291201/124275433-23dd9680-db60-11eb-9fe3-cfa3751b25b1.png)

I'm running paper 1.17#68

**Comment by LOOHP** [comment]
Try removing that option in the config to let it regenerate

**Comment by Zoro-6191** [comment]
ah yes, I must have messed it up while editting, my bad
