### ISSUE TITLE
ItemDrop hologram display fix for Slimefun

### ISSUE THREAD

**Issue by pianwan** [LOOHP/InteractionVisualizer#66]
Some plugin already has a drop item display function. If using InteractionVisualizer with them, it will cause this bug.

This is an Ancient pedestal in [Slimefun](https://github.com/Slimefun/Slimefun4) plugin.

![img1](https://user-images.githubusercontent.com/13903138/129230212-1eb40a8e-742b-4250-9e4b-72c2cda8e64d.png)

![img2](https://user-images.githubusercontent.com/13903138/129230231-084bfc6a-bf75-4c07-8fa5-3e46468677d1.png)

An easy way to fix it is using paper's `CreatureSpawnEvent.SpawnReason`. Check a dropping item's SpawnReason, whether it is `SpawnReason.CUSTOM`.

**Comment by LOOHP** [comment]
You can black list certain items in the config

**Comment by kn-km** [comment]
> You can black list certain items in the config

I do not want a normal drop item to lose its hologram. The hologram needs to be removed only while using Ancient pedestals.

**Comment by LOOHP** [comment]
Your suggestion is a good one, tho there are two main problems:
1. It only works on Paper and not on Spigot
2. It might block items from other plugins that shouldn't be block
I'm trying to come up with an alternative.
