### ISSUE TITLE
Hello, if you have time, can you make a GUI to switch the sub-items in the module?

### ISSUE THREAD

**Issue by Zz-886** [LOOHP/InteractionVisualizer#70]
Hello, if you have time, can you make a GUI to switch the sub-items in the module?

**Comment by LOOHP** [comment]
What do you mean by "switching sub-modules"?

**Comment by Zz-886** [comment]
![image](https://user-images.githubusercontent.com/55978588/130624707-e14f1232-52f3-4bca-a3db-4dd723d2558e.png)
Implement their switches in the GUI

**Comment by Zz-886** [comment]
Because some of them have not very good user experience.
Adding to the need for tests for bad English, this is too painful.

**Comment by Zz-886** [comment]
Forget it, I use the menu to make it myself
