### ISSUE TITLE
Suggestion: Toggle glow effect on Chest items

### ISSUE THREAD

**Issue by Blocker226** [LOOHP/InteractionVisualizer#8]
I'd like a configuration option to disable glow on items when they are being moved to and from chests so that they won't be visible through walls.

I'm willing to create a PR and contribute if needed. It's quite distracting noticing blips of red and green move around in occasional buildings.

**Comment by LOOHP** [comment]
Yea, that seemed a nice feature to have. And sure, feel free to do a PR! Or you can wait until I finish everything at hand first.

**Comment by LOOHP** [comment]
You know what, I don't really like the glowing feature, it kinda makes it different to other blocks, I think I'll just remove it.

**Comment by Blocker226** [comment]
Alright, thanks! Closing this now!
