### ISSUE TITLE
LightAPI Console Spam

### ISSUE THREAD

**Issue by Brickwrath** [LOOHP/InteractionVisualizer#80]
Tested with both main LightAPI and LightAPI-Fork, Minecraft 1.18.1 causes this console message to spam while users are crafting.
https://pastebin.com/897sUDB1

Is there any way to fix or disable this LightAPI interaction? (turning on `force-enable-legacy` returns that this action is not supported)

**Comment by LOOHP** [comment]
Try updating to the latest dev build first. (1.17.0.15 as of now)

**Comment by Brickwrath** [comment]
Can confirm that on latest Purpur, latest LightAPI and InteractionVisualizer 1.17.0.15 this error continues to occur.

**Comment by LOOHP** [comment]
Can you give 1.17.0.16 a try? I've made some slight changes that might solve this.

**Comment by Brickwrath** [comment]
Looks like 1.17.0.16 did the trick, thank you so much for the update(s)!
