### ISSUE TITLE
Unicode text shows incorrectly in the latest version 

### ISSUE THREAD

**Issue by SleepyAsh0191** [LOOHP/InteractionVisualizer#81]
![image](https://user-images.githubusercontent.com/64446140/151645726-3eec49f1-0b6b-43ec-a62f-862f914a730e.png)
![image](https://user-images.githubusercontent.com/64446140/151645733-77ed8df9-f45b-4ef1-9de8-b45113aea15d.png)
![image](https://user-images.githubusercontent.com/64446140/151645829-62a01193-887e-4f1c-ba5c-a11fce45fa3d.png)

the progress bar in furnace ,reload message and noteblock shows incorrect text and older version(1.16.3) don't have this problem

My server used Paper 1.18.1
Plugin version is InteractionVisualizer-1.17.1.6 uses zh_CN language
Operation system is Windows Server 2019(Chinese Version)

**Comment by SleepyAsh0191** [comment]
Once I deleted lang folder and Language_Repo folder and reload this plugin via Plugman, the text recover to correct state.
But when I executed `/interactionvisualizer reload` command, text shows incorrectly

**Comment by LOOHP** [comment]
Can you give 1.17.1.7 a try?

**Comment by SleepyAsh0191** [comment]
> Can you give 1.17.1.7 a try?

okay, I'll try tomorrow

**Comment by SleepyAsh0191** [comment]
Works Fine!
