### ISSUE TITLE
Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null

### ISSUE THREAD

**Issue by Bloodlex** [LOOHP/InteractionVisualizer#83]
Hello,

This is an error I've came across on the console last time: [https://pastebin.com/uxSLsV5B](https://pastebin.com/uxSLsV5B)

Could you please take a look at it?

Server version: Purpur 1.18.1 build 1547
Plugin version: 1.17.1

**Comment by LOOHP** [comment]
Can you give this build a try?
https://drive.google.com/file/d/1GZKqO_K0xBbCcC2S563gg4hCIJBMXEiw/view?usp=sharing

**Comment by Bloodlex** [comment]
> Can you give this build a try? https://drive.google.com/file/d/1GZKqO_K0xBbCcC2S563gg4hCIJBMXEiw/view?usp=sharing

Yes, sure - thank you. I will try and get back to you 🙂 .

**Comment by LOOHP** [comment]
Closed due to inactivity.
