### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by alexmcgowan112** [LOOHP/InteractionVisualizer#84]
Error occurred while enabling InteractionVisualizer v1.17.2.1 (Is it up to date?)
com.loohp.interactionvisualizer.libs.com.loohp.yamlconfiguration.libs.com.amihaiemil.eoyaml.exceptions.YamlReadingException: Could not parse YAML starting at line 352 . It should be a sequence (line should start with '-'), a mapping (line should contain ':') or it should be a plain scalar, but it has 373 lines, while a plain scalar should be only 1 line!

https://pastebin.com/wK1ZeHYt

**Comment by LOOHP** [comment]
Can you show me your config?

**Comment by alexmcgowan112** [comment]
https://pastebin.com/ZLH9QmEV

**Comment by LOOHP** [comment]
Have you tried resetting the config?

**Comment by alexmcgowan112** [comment]
Ok it seems like the issue stems from trying to use OverrideDisable on item drops for crafting tables. I removed that and it seems to work now. 
That being said, did I use that wrong or is that just broken? I wanted to allow crafting tables to display what's in the crafting table without the finished product flying at the player.

**Comment by LOOHP** [comment]
That option is a list
```yaml
OverridingDisabled:
- "interactionvisualizer:crafting_table"
```

**Comment by alexmcgowan112** [comment]
Alright that fixed it
