### ISSUE TITLE
[Suggest] Provide hooks for BookShelf & ShulkerBox & Jukebox

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#9]
I use both your BookShelf and InteractionVisualizer plugins at the same time, and I hope to provide hooks for BookShelf to allow us to have a box-like animation when we put the book into the shelf.

I hope the Shulker box can have the same effects of suspended objects as the box.

I hope to be able to add a new animation, when we put the record in Jukebox, we can display the suspended matter of the record on the jukebox.

**Comment by LOOHP** [comment]
Can you elaborate a little more on "box-like" animation?

**Comment by BackWheel** [comment]
Sorry i mean something like chest

**Comment by LOOHP** [comment]
Will be added along the way in future updates.
