### ISSUE TITLE
The hologram items can be pick up by player

### ISSUE THREAD

**Issue by Yaosanqi137** [LOOHP/InteractionVisualizer#96]
**(I'm a high school student in China,so my English is not so good )**
(我是一个中国的高中生,所以我的英语不是很好)

**Yesterday,a player in my server told me that the anvil have some trouble when they use it**
昨天,我服务器的一名玩家告诉我说铁砧在使用的时候有点问题
**They said that when the anvil breaks,thier item are  still exist.However,the hologram item are also exist,and they can pick it up**
他们说当铁砧坏掉的时候,他们的东西还存在,但是展示的东西也同样存在,并且他们还能拿起来
**That's mean that they can use this bug to duplicate item**
也就是说他们可以使用这个bug来复制物品
**And I heard that the other server  which installed this plugin also have this problem.** 
并且我发现其他安装了此插件的服务器也有一样的问题
**I hope you can fix it,thanks :)**
我希望你可以修复它,谢谢 ：）

**Comment by LOOHP** [comment]
That should be impossible as even if the armor stands displaying the item on the anvil failed to be removed, they are still virtual and don't exist on the server.
Perhaps I miss understood your meaning, do you mind providing a video clip to demonstrate what you mean?

**Comment by Yaosanqi137** [comment]
ok，please wait，im having dinner

**Comment by LOOHP** [comment]
Make sure you are in survival mode as well.

**Comment by LOOHP** [comment]
Are you sure it is an InteractionVisualizer (IV) bug? Have you tried to reproduce it with IV disabled?
I've just tested this on my test server and I couldn't reproduce it.

**Comment by Yaosanqi137** [comment]
ok，i will try again，thanks

**Comment by Yaosanqi137** [comment]
omg，this bug appeared again when i disabled IV
But I don’t understand why
OK,thank you,it’s my problem,I’m very sorry
