### ISSUE TITLE
Could not pass event PlayerMoveEvent to InteractionVisualizer

### ISSUE THREAD

**Issue by ErythroCraft** [LOOHP/InteractionVisualizer#97]
Hello

Got any problems on PlayerMoveEvent by using your plugin on my 1.19.4 spigot server.

server-version: dev-Spigot-b31949f-be8682a (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

plugin-version: InteractionVisualizer v1.18.3.0

[latest.log](https://github.com/LOOHP/InteractionVisualizer/files/11178060/latest.log)

**Comment by LOOHP** [comment]
Should be fixed in 1.18.4.0
