### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [LOOHP/InteractionVisualizer#98]
I hope your plugin will work with Folia, I love your plugin, but I'm sorry it doesn't work with Folia :(

**Comment by LOOHP** [comment]
I've been monitoring Folia for some time, some of my other plugins already do support it.
However, ProtocolLib doesn't support Folia yet. ProtocolLib/2281
We will have to wait for that.

**Comment by xiaoyueyoqwq** [comment]
> I've been monitoring Folia for some time, some of my other plugins already do support it. However, ProtocolLib doesn't support Folia yet. [dmulloy2/ProtocolLib#2281](https://github.com/dmulloy2/ProtocolLib/issues/2281) We will have to wait for that.

First of all thank you for your reply to me, thank you very much! I'm glad you'll consider Folia, as many plugin authors have rejected my requests:( Thank you in advance! My server and I really like your plugin, he added a lot of fun elements to make the server very lively and interesting, thank you! :)

**Comment by Hanmingxuan** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/tree/feature/folia-support

**Comment by x1aoren** [comment]
> 我一直在监视 Folia一段时间，我的其他一些插件已经支持它。但是，ProtocolLib 还不支持 Folia。[dmulloy2/ProtocolLib#2281](https://github.com/dmulloy2/ProtocolLib/issues/2281) 我们将不得不等待。

Do you know what's wrong?!
I went to the ProtocolLib development library today with a try and try mentality（ https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ ）
I installed it on Folia1.20.1. Guess what happened. It did not report any errors, ran successfully, and created a configuration file. You can take a look at the following pictures. If it's true, support Folia quickly!! Thank you!
![D89RD OG22DPBTG7W% Q}DW](https://github.com/LOOHP/InteractionVisualizer/assets/136235181/30d8662d-25c6-45ff-967d-0e8692d9c5d6)
![B8A _U5`U9ZPI4$Z(L{P3 Q](https://github.com/LOOHP/InteractionVisualizer/assets/136235181/e0895f7b-3ffe-4ffe-a909-7871671fead7)

**Comment by x1aoren** [comment]
> > > 我一直在监视 Folia一段时间，我的其他一些插件已经支持它。但是，ProtocolLib 还不支持 Folia。[dmulloy2/ProtocolLib#2281](https://github.com/dmulloy2/ProtocolLib/issues/2281) 我们将不得不等待。
> > 
> > 
> > Do you know what's wrong?!
> > I went to the ProtocolLib development library today with a try and try mentality（ https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ ）
> > I installed it on Folia1.20.1. Guess what happened. It did not report any errors, ran successfully, and created a configuration file. You can take a look at the following pictures. If it's true, support Folia quickly!! Thank you!
> > ![D89RD OG22DPBTG7W% Q}DW](https://user-images.githubusercontent.com/136235181/251157139-30d8662d-25c6-45ff-967d-0e8692d9c5d6.png)
> > ![B8A _U5`U9ZPI4$Z(L{P3 Q](https://user-images.githubusercontent.com/136235181/251157315-e0895f7b-3ffe-4ffe-a909-7871671fead7.png)
> 
> i try it remake it for folia too, but in my server player cannot send some message to server 😕 Too strange

Oh no. That's really bad

**Comment by Hanmingxuan** [comment]
Orz

**Comment by Hanmingxuan** [comment]
mark

**Comment by Q2297045667** [comment]
Currently, ProtocolLib runs stably on Folia. I would like to know if InteractionVisualizer has any plans to support Folia in the future
